--- A global object for managing the transfer of items and fluids from dispatching machines to receiving machines.
--- There are a total of 128 frequencies, and each one can have any number of devices assigned to it. This object stores
--- a table of all currently used frequencies, indexed by a 7 bit binary number held in a string. Each frequency has two
--- tables: one of fluid receivers, and one of item receivers. All such tables are an ordered list, indexed at 1.
---
--- When a device attempts to dispatch items or fluids, this object will attempt the following process:
---     list = (the list of eligible devices)
---     local device = list.remove(1) -- Remove the first element on the list
---     local first = device -- Preserve a reference to this first element
---     while (not device.can_accept()) do -- Check to see if the device can accept what is being dispatched. If not, loop.
---         list.add(device) -- Add the device onto the end of the list
---         device = list.remove(1) -- Remove the first entry from the list
---         if device == first do return "Fail" end -- We've come full circle and none can accept the item/fluids. Stop trying.
---     end
---     device.receive(the items/fluids being dispatched)
---     return "Success"
---
--TODO: Implement item transfer function
--TODO: Implement fluid transfer function.